# Generated by Django 4.0.3 on 2022-04-09 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=64)),
                ('employee_surname', models.CharField(max_length=64)),
                ('job', models.CharField(choices=[('Chief', 'Chief'), ('Handyman', 'Handyman')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='TargetDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('periodically', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=64)),
                ('user_lastname', models.CharField(max_length=64)),
                ('user_email', models.CharField(max_length=128)),
                ('phone', models.IntegerField(max_length=20)),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
                ('street', models.CharField(blank=True, max_length=128, null=True)),
                ('postcode', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.user')),
                ('target_date', models.ManyToManyField(to='timetable.targetdate')),
                ('teams', models.ManyToManyField(to='timetable.team')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.employee')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.user')),
            ],
        ),
    ]
