# Generated by Django 4.0.3 on 2022-04-23 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=64, verbose_name='Miasto'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Numer telefonu'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='postcode',
            field=models.CharField(blank=True, max_length=6, verbose_name='Kod pocztowy'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='street',
            field=models.CharField(blank=True, max_length=128, verbose_name='Ulica'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_name',
            field=models.CharField(max_length=64, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_surname',
            field=models.CharField(max_length=64, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job',
            field=models.CharField(choices=[('Chief', 'Brygadzista'), ('Handyman', 'Pracownik fizyczny')], max_length=8, verbose_name='Funkcja'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='comments',
            field=models.TextField(null=True, verbose_name='Uwagi'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Klient'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='Zaakceptowano'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.services', verbose_name='Rodzaj usługi'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='target_date',
            field=models.DateField(verbose_name='Termin wykonania'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='teams',
            field=models.ManyToManyField(to='timetable.team', verbose_name='Ekipa'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_name',
            field=models.CharField(max_length=128, verbose_name='Nazwa usługi'),
        ),
        migrations.AlterField(
            model_name='team',
            name='employees',
            field=models.ManyToManyField(to='timetable.employee', verbose_name='Pracownicy'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=64, verbose_name='Nazwa zespołu'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('target_date', 'service_type'), name='unique service_date'),
        ),
        migrations.AlterModelTable(
            name='reservation',
            table='timetable_reservation',
        ),
    ]
