# Generated by Django 4.0.3 on 2022-04-23 10:36

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_alter_customuser_city_alter_customuser_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='target_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date.today)], verbose_name='Termin wykonania'),
        ),
    ]
