# Generated by Django 4.0.3 on 2022-04-14 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_reservation_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='service_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='timetable.services'),
            preserve_default=False,
        ),
    ]
