# Generated by Django 4.0.3 on 2022-04-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_services_reservation_is_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_name',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
    ]
