# Generated by Django 4.0.3 on 2022-04-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_team_team_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='employees',
        ),
        migrations.AddField(
            model_name='team',
            name='employees',
            field=models.ManyToManyField(to='timetable.employee'),
        ),
    ]
